Point to open surce deps - 3
pulp-platform/carfield pull request #153
Opened 2023-09-22 12:41 UTC by alex96295

In this PR, we bump to open source version of spatz

- [x] `spatz`

2023-09-22 14:06 UTC, micprog requested changes
May need a fix in spatz to add back the now missing `riscv_instr.sv` file, or the following addition to the `carfield.mk` file.

```diff
diff --git a/carfield.mk b/carfield.mk
index d61861c..0839135 100644
--- a/carfield.mk
+++ b/carfield.mk
@@ -244,6 +244,7 @@ car-hw-init: spatz-hw-init chs-hw-init
 
 .PHONY: spatz-hw-init
 spatz-hw-init:
+       $(MAKE) -C $(SPATZCL_ROOT) hw/ip/snitch/src/riscv_instr.sv
        $(MAKE) -C $(SPATZCL_MAKEDIR) -B SPATZ_CLUSTER_CFG=$(CAR_HW_DIR)/cfg/spatz_carfield.hjson bootrom
 
 .PHONY: chs-hw-init
```

2023-09-26 12:22 UTC, micprog commented
Spatz bump also handled in #151

2023-09-26 16:07 UTC, alex96295 commented
> Spatz bump also handled in #151

I would do the bump here, merge this one and then #151

2023-09-26 16:14 UTC, alex96295 commented
Rebased onto main

2023-09-26 16:19 UTC, micprog approved these changes
LGTM 👍

2023-09-27 05:59 UTC, merged