Update l2_wrap.sv
pulp-platform/carfield pull request #50
Opened 2023-05-22 05:41 UTC by husterZC

Modify L2_wrap to align with the SoC reset scheme. Here I add one global power reset signal, which connects to CDC in the wrap.

2023-05-22 06:03 UTC, alex96295 approved these changes
lgtm

2023-05-22 22:18 UTC, bluewww requested changes
I don't think this PR will work as is.

The fundamental problem is that currently the L2 is in the same clock domain as the host. This means we cannot clock gate L2 for doing the reset sequence we defined since there simply is not clockgate.

2023-05-23 11:32 UTC, luca-valente commented on hw/carfield.sv
> +  .clks_i({periph_clk_i, alt_clk_i, alt_clk_i, alt_clk_i, alt_clk_i, host_clk_i}),
I think we should negate them, if the `FF` reset value is 0.

2023-05-23 16:45 UTC, husterZC commented
The L2 may not be in the same clock domain of host (1GHz). I synthesized the L2 at the slow-slow corner, which even the SRAM Macro itself needs more than 1300ps clock period, and now L2 is save to work at 500MHz.

2023-05-23 17:26 UTC, alex96295 commented
We are adding L2 in the `alt_clk_i` clock domain, and the floating point cluster in the host clock domain. 

Any further change will be addressed in a future PR

2023-05-23 17:33 UTC, merged